### PR TITLE
Dylan duncanv2

### PR DESCRIPTION
**Pull request by kngrace**

### CODE REVIEW

**Comment by kngrace** [comment]
As per Dylan's request, I am creating a pull request for V2 to be merged into the main branch. -Kirsten

**Comment by l2mIam** [comment]
Anyone figure out how to host on git

**Comment by kngrace** [comment]
Our page will appear at: http://l2mlam.github.io/OrangeOne

But first, Loren must set it up by following these instructions:
https://pages.github.com/

Since I do not have access to "settings" :-(

Loren, can you try those at??

Kirsten Grace
Club President, Women in Computing Sciences
Computer Science and Systems Undergraduate
University of Washington Tacoma
kngrace@uw.edu  kirstengrace@gmail.com

**Comment by l2mIam** [comment]
done, here's the corrected link (it's an "i" not an "l"):
http://l2miam.github.io/OrangeOne

On Fri, Feb 20, 2015 at 5:29 PM, kngrace notifications@github.com wrote:

> Our page will appear at: http://l2mlam.github.io/OrangeOne
> 
> But first, Loren must set it up by following these instructions:
> https://pages.github.com/
> 
> Since I do not have access to "settings" :-(
> 
> Loren, can you try those at??
> 
> Kirsten Grace
> Club President, Women in Computing Sciences
> Computer Science and Systems Undergraduate
> University of Washington Tacoma
> kngrace@uw.edu kirstengrace@gmail.com
> 
> On Fri, Feb 20, 2015 at 2:17 PM, l2mIam notifications@github.com wrote:
> 
> > Anyone figure out how to host on git
> > On Feb 20, 2015 1:41 PM, "kngrace" notifications@github.com wrote:
> > 
> > > ---
> > > 
> > > You can view, comment on, or merge this pull request online at:
> > > 
> > > https://github.com/l2mIam/OrangeOne/pull/3
> > > Commit Summary
> > > - Updating to current
> > > - NPCMobus
> > > - Small change
> > > - made more teachers
> > > - Added Chin
> > > - started working on the input button. needs to capture a key release
> > >   and not a key press or else the displayed image with flash.
> > > 
> > > File Changes
> > > - _A_ about.html
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-0 (33)
> > > - _A_ css/fontfaces.css
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-1 (17)
> > > - _A_ css/main.css
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-2 (205)
> > > - _A_ css/mobile.css
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-3 (62)
> > > - _M_ css/style.css
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-4 (4)
> > > - _A_ fonts/AlfaSlabOFL.txt
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-5 (93)
> > > - _A_ fonts/AlfaSlabOne-Regular.ttf
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-6 (0)
> > > - _A_ fonts/IndieFlower.ttf
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-7 (0)
> > > - _A_ fonts/IndieFlowerOFL.txt
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-8 (92)
> > > - _A_ fonts/Orbitron-Black.ttf
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-9 (0)
> > > - _A_ fonts/OrbitronOFL.txt
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-10 (93)
> > > - _A_ game.html
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-11 (100)
> > > - _A_ img/Alden-plain.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-12 (0)
> > > - _A_ img/UWBookStoreInterior11x19.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-13 (0)
> > > - _A_ img/UWTmap1.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-14 (0)
> > > - _A_ img/alden.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-15 (0)
> > > - _A_ img/arrows.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-16 (0)
> > > - _A_ img/chin.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-17 (0)
> > > - _A_ img/mobus.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-18 (0)
> > > - _A_ img/purple_orc.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-19 (0)
> > > - _A_ img/uwe.png
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-20 (0)
> > > - _A_ img/uwt.jpg
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-21 (0)
> > > - _A_ img/uwt2.jpg
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-22 (0)
> > > - _M_ index.html
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-23 (39)
> > > - _A_ js/game.js
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-24 (386)
> > > - _A_ js/gamecontroller.js
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-25 (1311)
> > > - _D_ js/index.js
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-26 (289)
> > > - _A_ js/input.js
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-27 (19)
> > > - _A_ js/modernizr.js
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-28 (9)
> > > - _A_ js/overlay.js
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-29 (76)
> > > - _A_ js/uwetech.loader.js
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-30 (134)
> > > - _A_ sounds/GroundhogDay1.mp3
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-31 (0)
> > > - _A_ sounds/bowdownuw.mp3
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-32 (0)
> > > - _A_ sounds/bowdownuw.ogg
> > >   https://github.com/l2mIam/OrangeOne/pull/3/files#diff-33 (0)
> > > 
> > > Patch Links:
> > > - https://github.com/l2mIam/OrangeOne/pull/3.patch
> > > - https://github.com/l2mIam/OrangeOne/pull/3.diff
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/l2mIam/OrangeOne/pull/3.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/l2mIam/OrangeOne/pull/3#issuecomment-75329721.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/l2mIam/OrangeOne/pull/3#issuecomment-75348412.

## 

Thanks,

Loren Milliman
loren.milliman@gmail.com
206-290-2569 (cel/msg 24/7)

**Pull request merged**
