### PR TITLE
Npc impassible

### PR DESCRIPTION
**Pull request by dyhansen**

### CODE REVIEW

**Comment by l2mIam** [comment]
I just noticed an issue...I'M TRAPPED!  Need to have the NPC move off after
a short pause (one second?)
[image: Inline image 1]

On Tue, Feb 24, 2015 at 12:11 PM, dyhansen notifications@github.com wrote:

> Merged #13 https://github.com/l2mIam/OrangeOne/pull/13.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/l2mIam/OrangeOne/pull/13#event-241210170.

## 

Thanks,

Loren Milliman
loren.milliman@gmail.com
206-290-2569 (cel/msg 24/7)

**Comment by dyhansen** [comment]
You get stuck you lose, simple as that.

**Comment by kngrace** [comment]
Haha, that is hilarious. Horrible but hilarious.

**Comment by kngrace** [comment]
I can imagine it now... "You've been cornered by a professor! GAME OVER"

**Pull request merged**
